title: Ryan # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Life-long learner and aspiring game developer. Studied computer science at Earlham College for 3 years with a minor in studio painting.
  <br><br>
  Currently at iD Tech serving as an online instructor. Working remotely, I mentor aspiring young developers and creatives in topics such as game design and programming, and 3D modeling.
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
