title: Ryan # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Doing preceeds learning. In that spirit, I am a
  lifelong do-er. I am currently working towards 
  a bachelor's degree in software engineering at
  Rochester Institute of Technology.
  <br><br>
  Previously, I worked with iD Tech as an online 
  instructor, where I mentored aspiring young 
  developers and creatives in topics such as 
  game design, programming, and 3D modeling.
  <br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
